[workspace]
members = ["crates/toargv", "crates/toargv-template"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.88"
license = "MIT"
repository = "https://github.com/binado/toargv"
homepage = "https://github.com/binado/toargv"

[workspace.dependencies]
toargv-template = { version = "0.1.0", path = "crates/toargv-template" }
