[package]
name = "toargv-template"
description = "Argument template parser and expander for toargv"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/toargv-template"
readme = "README.md"
keywords = ["cli", "configuration", "arguments", "template", "parser"]
categories = ["command-line-utilities", "config", "parser-implementations"]

[dependencies]
jaq-core = "3.1"
jaq-json = { version = "=2.0.2", features = ["serde"] }
jaq-std = "3.0"
serde_json = "1.0"
thiserror = "2.0"
